batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: E:/Capstone/sentenceRecognition/models\202409170903
train_epochs: 1000
train_workers: 20
vocab: '"f9KjQ3q.UH *2i,k;GWl?:xX''BoPZnSEeyJmaOgMwYNAru/v1TbL(!sch)C-RI6z7D5dV40tF8+p#&'
width: 1408
