batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: E:/Capstone/sentenceRecognition/models\202409170904
train_epochs: 1000
train_workers: 20
vocab: OgQAoi"bl0 kFD)dKz7T3.ncLY698Zy!I#+u:wrpeC/?2ta*4vV5'E-qjM,fsUB(RSmGHJWX1&xPN;h
width: 1408
