batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: E:/Capstone/sentenceRecognition/models\202409170908
train_epochs: 1000
train_workers: 20
vocab: ' uOJA#5F)CR,cHZ''QzPg1&S;d*2/aIlLeKkxnM6Vt.b3owp8?!rYys-WEU9Gmi0T+v:(7hfNX"qB4Dj'
width: 1408
