batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: E:/Capstone/sentenceRecognition/models\202409170906
train_epochs: 1000
train_workers: 20
vocab: vu'Dm.1c?p:YI*2MN!dO90BFWZ"Rw,&)aLUxsi35PH67eXKE;qkTGoJ+fjznCrh QAb84#-(VlygS/t
width: 1408
